# Generated by Django 4.1.1 on 2023-01-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0002_alter_tag_createdby_alter_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ID', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('createdBy', models.IntegerField(blank=True, default=None, null=True)),
                ('addedAt', models.DateTimeField(auto_now=True)),
                ('tag_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
        ),
    ]
