# Generated by Django 4.1.1 on 2023-01-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_createdby_alter_tag_description'),
        ('recipe_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='tag_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='tag.tag'),
        ),
    ]
