# Generated by Django 4.1.1 on 2023-01-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_tag', '0003_alter_recipetag_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tag_ID',
            new_name='tag_id',
        ),
    ]
