# Generated by Django 4.1.1 on 2023-01-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_tag', '0004_rename_tag_id_recipetag_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tag_id',
            new_name='tag_ID',
        ),
    ]
