# Generated by Django 4.1.1 on 2023-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('createdBy', models.IntegerField(null=True)),
                ('addedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
